name: Publish docker image to server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag makersmatch-frontend:latest
  
      - name: Save the docker image
        run: | 
          docker image save -o makersmatch-frontend.tar makersmatch-frontend:latest
          chmod 664 makersmatch-frontend.tar
  
      - name: Copy the docker image to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "makersmatch-frontend.tar"
          target: ./

      - name: Remove running docker container and start new docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop makersmatchfrontend
            docker rmi makersmatch-frontend:latest
            docker load -i makersmatch-frontend.tar
            docker run -d -p 8083:3000 --name makersmatchfrontend --restart always makersmatch-frontend:latest
          